image: python:alpine

stages:
  - build
  - deploy

before_script:
  - pip install mkdocs

generate:
  stage: build
  script:
    - mkdocs build
  artifacts:
    paths:
      - site

deploy to production:
  environment: production
  image: python:latest
  stage: deploy
  dependencies:
    - generate      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  before_script:
    - pip install awscli
  script:
    - aws s3 sync --delete site s3://s3.developer.tripgo.com
  only:
    - master

deploy to beta:
  environment: beta
  image: python:latest
  stage: deploy
  dependencies:
    - generate      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  before_script:
    - pip install awscli
  script:
    - aws s3 sync --delete site s3://s3.beta.developer.tripgo.com
  only:
    - beta

deploy to staging:
  environment: staging
  image: python:latest
  stage: deploy
  dependencies:
    - generate      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  before_script:
    - pip install awscli
  script:
    - aws s3 sync --delete site s3://s3.staging.developer.tripgo.com
  except:
    - master
    - beta

