deploy to production:
  environment: production
  image: python:latest
  script:
    - pip install mkdocs
    - pip install awscli
    - mkdocs build
    - aws s3 sync --delete site s3://s3.developer.tripgo.com
  only:
    - master

deploy to beta:
  environment: beta
  image: python:latest
  script:
    - pip install mkdocs
    - pip install awscli
    - mkdocs build
    - aws s3 sync --delete site s3://s3.beta.developer.tripgo.com
  only:
    - beta

deploy to staging:
  environment: staging
  image: python:latest
  script:
    - pip install mkdocs
    - pip install awscli
    - mkdocs build
    - aws s3 sync --delete site s3://s3.staging.developer.tripgo.com
  except:
    - master
    - beta

