variables:
  S3_STAGING_BUCKET_NAME: "s3.staging.developer.tripgo.com"
  S3_BETA_BUCKET_NAME: "s3.beta.developer.tripgo.com"
  S3_PROD_BUCKET_NAME: "s3.developer.tripgo.com"

image: python:alpine

before_script:
  - pip install mkdocs

generate:
  script:
    - mkdocs build

deploy to production:
  environment: production
  image: python:latest
  script:
    - pip install awscli
    - aws s3 sync --delete site s3://${S3_PROD_BUCKET_NAME}
  only:
    - master

deploy to beta:
  environment: beta
  image: python:latest
  script:
    - pip install awscli
    - aws s3 sync --delete site s3://${S3_BETA_BUCKET_NAME}
  only:
    - beta

deploy to staging:
  environment: staging
  image: python:latest
  script:
    - pip install awscli
    - aws s3 sync --delete site s3://${S3_STAGING_BUCKET_NAME}
  except:
    - master
    - beta

