variables:
  S3_STAGING_BUCKET_NAME: "staging.developer.tripgo.com"
  S3_BETA_BUCKET_NAME: "beta.developer.tripgo.com"
  S3_PROD_BUCKET_NAME: "developer.tripgo.com"

image: python:alpine

before_script:
  - pip install mkdocs

generate:
  script:
    - mkdocs build

deploy to production:
  environment: production
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp ./ s3://$S3_PROD_BUCKET_NAME/ --recursive --exclude "*" --include "site/*"
  only:
    - master

deploy to beta:
  environment: beta
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp ./ s3://$S3_BETA_BUCKET_NAME/ --recursive --exclude "*" --include "site/*"
  only:
    - beta

deploy to staging:
  environment: staging
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp ./ s3://$S3_STAGING_BUCKET_NAME/ --recursive --exclude "*" --include "site/*"
  except:
    - master
    - beta

