image: python:alpine

before_script:
  - pip install mkdocs

generate:
  script:
    - mkdocs build
  artifacts:
    paths:
      - site

deploy to production:
  environment: production
  image: python:latest
  script:
    - pip install awscli
    - aws s3 sync --delete site s3://s3.developer.tripgo.com
  only:
    - master

deploy to beta:
  environment: beta
  image: python:latest
  script:
    - pip install awscli
    - aws s3 sync --delete site s3://s3.beta.developer.tripgo.com
  only:
    - beta

deploy to staging:
  environment: staging
  image: python:latest
  script:
    - pip install awscli
    - aws s3 sync --delete site s3://s3.staging.developer.tripgo.com
  except:
    - master
    - beta

